"use client";

import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'ar';

interface Translation {
    en: string;
    fr: string;
    ar?: string;
}

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (translation: Translation) => string;
    isRTL: boolean;
}

const ARABIC_OVERRIDES: Record<string, string> = {
    // Core navigation and profile
    'Home': 'الرئيسية',
    'Profile': 'الملف الشخصي',
    'Orders': 'الطلبات',
    'All Orders': 'كل الطلبات',
    'My Heroes': 'أبطالي',
    'Dashboard': 'لوحة التحكم',
    'Help': 'مساعدة',
    'Orders History': 'سجل الطلبات',
    'Order history': 'سجل الطلبات',
    'My information': 'معلوماتي',
    'Switch to Provider': 'التحويل إلى وضع مقدم الخدمة',
    'Switch to Client Mode': 'التحويل إلى وضع العميل',
    'Become a Bricoler!': 'كن مقدم خدمة!',
    'Languages and currency': 'اللغات والعملة',
    'Share and earn!': 'شارك واربح!',
    'Promocodes': 'أكواد الخصم',
    'Notifications': 'الإشعارات',
    'F.A.Q.': 'الأسئلة الشائعة',
    'Client account': 'حساب عميل',
    'Provider account': 'حساب مقدم خدمة',
    'Admin account': 'حساب إداري',
    'Log out': 'تسجيل الخروج',
    'Log in or sign up': 'تسجيل الدخول أو إنشاء حساب',
    'New': 'جديد',
    'Recommended': 'موصى به',
    'Search...': 'بحث...',
    'Settings': 'الإعدادات',
    'Support': 'الدعم',
    'Privacy Policy': 'سياسة الخصوصية',
    'Terms of Use': 'شروط الاستخدام',

    // Cities
    'Casablanca': 'الدار البيضاء',
    'Marrakech': 'مراكش',
    'Essaouira': 'الصويرة',
    'Agadir': 'أغادير',
    'Tangier': 'طنجة',
    'Rabat': 'الرباط',
    'Fes': 'فاس',

    // Common UI Actions
    'Select': 'اختر',
    'Confirm': 'تأكيد',
    'Cancel': 'إلغاء',
    'Continue': 'استمرار',
    'Back': 'رجوع',
    'Save': 'حفظ',
    'Edit': 'تعديل',
    'Delete': 'حذف',
    'Apply': 'تطبيق',
    'Close': 'إغلاق',
    'Send': 'إرسال',
    'Update': 'تحديث',
    'Next': 'التالي',
    'Finish': 'إنهاء',
    'Select & Continue': 'اختيار ومتابعة',

    // Client home hero + tabs
    'Book trusted help for home tasks': 'احجز مساعدة موثوقة لمهام منزلك',
    'Trending': 'رائج',
    'Pool cleaning': 'تنظيف المسبح',
    'Pets care': 'رعاية الحيوانات',
    'Filter Cleaning': 'تنظيف الفلتر',
    'Chemical Balancing': 'توازن كيميائي',
    'Keep your pool crystal clear and safe for everyone.': 'حافظ على مسبحك صافياً وآمناً للجميع.',
    'Specialized chemical balancing for various pool types.': 'توازن كيميائي متخصص لمختلف أنواع المسابح.',

    // Services (Main Categories)
    'Handyman': 'إصلاحات منزلية',
    'Bricoleur': 'مقدم خدمة',
    'Cleaning': 'تنظيف',
    'Plumbing': 'سباكة',
    'Electricity': 'كهرباء',
    'Painting': 'صباغة',
    'Furniture assembly': 'تركيب الأثاث',
    'Moving help': 'مساعدة في النقل',
    'Mounting': 'تثبيت وتوريد',
    'Gardening': 'بستنة',
    'Babysitting': 'جليسة أطفال',
    'Elderly assistance': 'رعاية كبار السن',
    'Car with driver': 'سيارة مع سائق',
    'Car rental': 'كراء السيارات',
    'Courier / delivery': 'توصيل / إرساليات',
    'Airport pickup': 'النقل من المطار',
    'Intercity transport': 'نقل بين المدن',
    'Appliances': 'الأجهزة المنزلية',
    'Cooking': 'طبخ',
    'Meal prep': 'تحضير الطعام',
    'Home Repairs': 'إصلاحات منزلية',
    'Errands & small deliveries': 'قضاء حاجيات وتوصيل',
    'Glass cleaning': 'تنظيف الزجاج',
    'Elderly care': 'رعاية المسنين',

    // Booking Flow & Order Details
    'Activity': 'النشاط',
    'Calendar': 'التقويم',
    'Order details': 'تفاصيل الطلب',
    'Duration': 'المدة',
    'Price': 'السعر',
    'Service': 'الخدمة',
    'Payment': 'الدفع',
    'Cash': 'نقداً',
    'Location': 'الموقع',
    'Description': 'الوصف',
    'Need Description': 'وصف الطلب',
    'Photos': 'الصور',
    'Payment Method': 'طريقة الدفع',
    'Cash on delivery': 'الدفع عند الاستلام',
    'Summary': 'ملخص الطلب',
    'Task Fee': 'تكلفة الخدمة',
    'Lbricol Fee': 'رسوم لبريكول',
    'Total': 'الإجمالي',
    'Pending orders': 'طلبات قيد الانتظار',
    'New Orders': 'طلبات جديدة',
    'All': 'الكل',
    'Today': 'اليوم',
    'This Week': 'هذا الأسبوع',
    'Track your orders': 'تابع طلباتك',
    'Your ongoing orders will be listed here': 'ستظهر هنا طلباتك الجارية',
    'Continue your order': 'أكمل طلبك',
    'No carts yet': 'لا توجد سلات بعد',
    "Orders you don't complete will appear here": 'الطلبات التي لم تُكملها ستظهر هنا',
    'Check your order history': 'عرض سجل الطلبات',
    'Re-book Bricolers you love': 'أعد حجز مقدمي الخدمة المفضلين لديك',
    'No Heroes Yet': 'لا يوجد أبطال بعد',
    'Once you complete jobs with Bricolers, they will appear here.': 'بعد إكمال مهام مع مقدمي الخدمة، سيظهرون هنا.',
    'Book Slots': 'احجز موعداً',
    'No notifications yet': 'لا توجد إشعارات بعد',
    'Updates about your orders and referrals will appear here.': 'ستظهر هنا تحديثات طلباتك وبرامج الإحالة.',
    'unread': 'غير مقروءة',
    'Date': 'التاريخ',
    'Time': 'الوقت',
    'Address': 'العنوان',
    'When do you need them?': 'متى تحتاجهم؟',
    'What do you need help with?': 'بماذا تحتاج المساعدة؟',

    // Statuses
    'Pending': 'في الانتظار',
    'Confirmed': 'مؤكد',
    'Accepted': 'مقبول',
    'In Progress': 'قيد التنفيذ',
    'Done': 'مكتمل',
    'Completed': 'مكتمل',
    'Cancelled': 'ملغي',
    'Declined': 'مرفوض',
    'Negotiating': 'تفاوض',

    // Provider Specific
    'Performance': 'الأداء',
    'Earnings': 'الأرباح',
    'Availability': 'ساعات العمل',
    'My Services': 'خدماتي',
    'New Mission': 'مهمة جديدة',
    'Scheduled': 'مبرمج',
    'Programmed': 'مبرمج',
    'Waiting Client': 'في انتظار العميل',
    'Accept': 'قبول',
    'Decline': 'رفض',
    'Counter offer': 'عرض مقابل',
    'Active Orders': 'طلبات نشطة',
    'History': 'السجل',

    // Task Sizes & Scopes
    'Small': 'صغير',
    'Medium': 'متوسط',
    'Large': 'كبير',
    'Est: 1 hr': 'حوالي ساعة واحدة',
    'Est: 2 hrs': 'حوالي ساعتين',
    'Est: 4+ hrs': '4 ساعات أو أكثر',
    "How large is the space?": "ما هي مساحة المكان؟",
    "Studio / 1 Bedroom": "استوديو / غرفة واحدة",
    "Basic cleaning for a small space.": "تنظيف أساسي لمساحة صغيرة.",
    "2-3 Bedrooms": "2-3 غرف نوم",
    "Standard cleaning for a medium home.": "تنظيف عادي لمنزل متوسط.",
    "4+ Bedrooms / Deep Clean": "4 غرف أو أكثر / تنظيف عميق",
    "Extensive cleaning for large homes.": "تنظيف شامل للمنازل الكبيرة.",
    "What's the scope of the task?": "ما هو حجم المهمة؟",
    "Few Items / Studio": "قطع قليلة / استوديو",
    "Small move, boxes, or quick errand.": "نقل صغير، صناديق أو غرض سريع.",
    "1-2 Bedroom Apartment": "شقة من غرفة أو غرفتين",
    "Standard move requiring a van.": "نقل عادي يتطلب شاحنة صغيرة.",
    "3+ Bedroom / Full House": "3 غرف أو أكثر / منزل كامل",
    "Large scale move requiring multiple trips or large truck.": "نقل كبير يتطلب عدة رحلات أو شاحنة كبيرة.",
    "What's the scope of the problem?": "ما هو حجم المشكلة؟",
    "Minor Issue / Quick Fix": "مشكلة بسيطة / إصلاح سريع",
    "Simple fix like a small leak or replacing an outlet.": "إصلاح بسيط مثل تسرب صغير أو تغيير مأخذ كهربائي.",
    "Standard / Installation": "عادي / تركيب",
    "New installations or moderate repairs.": "تركيبات جديدة أو إصلاحات متوسطة.",
    "Major / Unknown": "مشكلة كبرى / غير معروف",
    "Complex issues or full system replacements.": "مشاكل معقدة أو استبدال كامل للنظام.",
    "How long is the care needed?": "ما هي مدة الرعاية المطلوبة؟",
    "Short Term (1-4 hrs)": "فترة قصيرة (1-4 ساعات)",
    "Brief assistance or babysitting slot.": "مساعدة وجيزة أو جليسة أطفال لفترة قصيرة.",
    "Half Day (4-8 hrs)": "نصف يوم (4-8 ساعات)",
    "Standard care for a morning, afternoon or evening.": "رعاية عادية للصباح أو المساء.",
    "Full Day / Overnight": "يوم كامل / مبيت",
    "Comprehensive care over an extended period.": "رعاية شاملة لفترة ممتدة.",
    "How much furniture needs assembly?": "كم عدد الأثاث الذي يحتاج للتركيب؟",
    "1-2 Small Items": "قطعة أو قطعتين صغيرتين",
    "Quick assembly of simple items.": "تركيب سريع لقطع بسيطة.",
    "1 Large / 3-4 Small Items": "قطعة كبيرة / 3-4 قطع صغيرة",
    "Standard assembly like a bed frame or wardrobe.": "تركيب عادي مثل سرير أو خزانة ملابس.",
    "Full Room / Complex Items": "غرفة كاملة / قطع معقدة",
    "Multiple large pieces or complex systems.": "عدة قطع كبيرة أو أنظمة معقدة.",
    "What is the scope of the repairs?": "ما هو حجم الإصلاحات؟",
    "Minor Fix / Single Issue": "إصلاح بسيط / مشكلة واحدة",
    "Quick repair or adjustment.": "إصلاح أو تعديل سريع.",
    "Standard Repair / Few Issues": "إصلاح عادي / عدة مشاكل",
    "Multiple small fixes or a standard project.": "عدة إصلاحات صغيرة أو مشروع عادي.",
    "Multiple Repairs / Half Day": "إصلاحات متعددة / نصف يوم",
    "Extensive repair work across the property.": "عمل إصلاحات شاملة في العقار.",
    "What needs to be mounted?": "ما الذي يجب تركيبه؟",
    "1-2 Items / Picture Frames": "قطعة أو قطعتين / إطارات صور",
    "Hanging pictures, mirrors, or small shelves.": "تعليق صور، مرايا أو رفوف صغيرة.",
    "TV / Multiple Shelves": "تلفاز / عدة رفوف",
    "Mounting a TV or several shelving units.": "تركيب تلفاز أو عدة رفوف.",
    "Complex / Heavy / Multiple Rooms": "معقد / ثقيل / عدة غرف",
    "Heavy mounting or covering multiple rooms.": "تركيب ثقيل أو يغطي عدة غرف.",
    "What is the painting scope?": "ما هو حجم الصباغة؟",
    "Touch-ups / Single Wall": "رتوش / حائط واحد",
    "Minor paint repairs or an accent wall.": "إصلاحات صباغة بسيطة أو حائط واحد.",
    "Single Room": "غرفة واحدة",
    "Painting walls of a standard bedroom or living room.": "صباغة جدران غرفة نوم أو صالون.",
    "Multiple Rooms / Exterior": "عدة غرف / واجهة خارجية",
    "Larger painting projects, multiple rooms or exterior work.": "مشاريع صباغة كبيرة، عدة غرف أو عمل خارجي.",
    "What gardening work is required?": "ما هو عمل البستنة المطلوب؟",
    "Basic Mowing / Weeding": "قص عشب بسيط / إزالة الأعشاب الضارة",
    "Simple lawn maintenance and weed removal.": "صيانة بسيطة للعشب وإزالة الأعشاب.",
    "Yard Cleanup / Trimming": "تنظيف الحديقة / تشذيب",
    "Pruning trees/shrubs and general yard tidying.": "تقليم الأشجار وتنظيف عام للحديقة.",
    "Full Landscaping": "تنسيق كامل للحديقة",
    "Major yard overhaul, planting, or extensive clearing.": "تجديد شامل للحديقة، زراعة أو تنظيف مكثف.",
    "How many windows/surfaces?": "كم عدد النوافذ/الأسطح؟",
    "Few Windows / Minor": "نوافذ قليلة / عمل بسيط",
    "Cleaning glass in a small apartment or storefront.": "تنظيف الزجاج في شقة صغيرة أو محل تجاري.",
    "Standard House": "منزل عادي",
    "Full interior/exterior window cleaning for a typical home.": "تنظيف كامل للنوافذ (داخلي/خارجي) لمنزل عادي.",
    "Large House / High glass": "منزل كبير / نوافذ عالية",
    "Extensive glass cleaning requiring ladders or specialized tools.": "تنظيف زجاج شامل يتطلب سلالم أو أدوات خاصة.",
    "How big is your pool?": "ما هو حجم المسبح؟",
    "Small / Plunge Pool": "مسبح صغير / مسبح غطس",
    "Chemical check and minor surface skimming.": "فحص المواد الكيميائية وتنظيف سطحي بسيط.",
    "Standard In-ground": "مسبح عادي محفور",
    "Full vacuum, filter clean, and chemical balance.": "تنظيف كامل بالمكنسة، تنظيف الفلتر وتوازن كيميائي.",
    "Large / Green-to-Clean": "مسبح كبير / من أخضر إلى نظيف",
    "Extensive cleaning for large pools or water restoration.": "تنظيف شامل للمسابح الكبيرة أو معالجة المياه.",
    "What level of care is needed?": "ما هو مستوى الرعاية المطلوب؟",
    "Walk / Quick Visit": "نزهة / زيارة سريعة",
    "30-60 min walk or feeding check-in.": "نزهة 30-60 دقيقة أو فحص إطعام.",
    "Half Day Sitting": "رعاية نصف يوم",
    "Pet sitting and companionship for a few hours.": "رعاية ومرافقة للحيوان لعدة ساعات.",
    "Comprehensive care for the entire day or night.": "رعاية شاملة لليوم أو الليلة بالكامل.",
    "What's the size of your Task?": "ما هو حجم المهمة؟",
    'Scheduled jobs': 'المهام المبرمجة',
    'No missions scheduled': 'لا توجد مهام مبرمجة',
    'Your upcoming missions will be listed here': 'ستظهر مهامك القادمة هنا',
    'Pending Jobs': 'مهام قيد الانتظار',
    'No jobs in progress': 'لا توجد مهام قيد التنفيذ',
    'Missions you are currently executing will appear here': 'ستظهر هنا المهام التي تنفذها حالياً',
    'Jobs Delivered': 'مهام مكتملة',
    'No jobs delivered yet': 'لا توجد مهام مكتملة بعد',
    'Missions you successfully complete will appear here': 'ستظهر هنا المهام التي أكملتها بنجاح',
    'Need to review past missions?': 'هل تريد مراجعة مهامك السابقة؟',
    'Check my mission history': 'اطلع على سجل مهامي',
    'No history yet': 'لا يوجد سجل بعد',
    'Your completed and cancelled orders will appear here.': 'ستظهر هنا طلباتك المكتملة والملغاة.',
    'No missions today': 'لا توجد مهام اليوم',
    'Enjoy your day off or check other days for scheduled tasks.': 'استمتع بيومك أو تحقق من الأيام الأخرى.',
    'Set your availability slots for this day.': 'حدد أوقات توفرك لهذا اليوم.',
    'Add custom slots': 'إضافة أوقات مخصصة',
    'Morning': 'الصباح',
    'Afternoon': 'الظهيرة',
    'Evening': 'المساء',
    'Active Offer': 'عرض نشط',
    'Delivered': 'مكتمل',
    'Rate your experience': 'قيم تجربتك',
    'Write a quick review (optional)...': 'اكتب تقييماً سريعاً (اختياري)...',
    'Submit Review': 'إرسال التقييم',
    'New Offer Received': 'تم استلام عرض جديد',
    'jobs': 'مهام',
    'PRICE PROPOSAL': 'عرض السعر',
    'Accept Offer': 'قبول العرض',
    'Counter': 'عرض مقابل',
    'Propose your price': 'اقترح سعرك',
    'Send Counter-offer': 'إرسال عرض مقابل',
    'Back to offer': 'العودة للعرض',
    'Deal Confirmed!': 'تم الاتفاق!',
    'Proceed to Dashboard': 'الانتقال إلى لوحة التحكم',
    'Messages': 'الرسائل',
    'Login to see messages': 'سجل الدخول لرؤية الرسائل',
    'Keep track of your conversations and project updates.': 'تابع محادثاتك وتحديثات مشاريعك.',
    'Send a message to start': 'أرسل رسالة للبدء',
    'Chat': 'دردشة',
    'Flexible': 'مرن',
    'On track': 'في المسار الصحيح',
    'TASK DESCRIPTION': 'وصف المهمة',
    'Start chatting about your service': 'ابدأ الدردشة حول خدمتك',
    'Write a message...': 'اكتب رسالة...',
    'Messages about your services will appear here.': 'ستظهر هنا الرسائل المتعلقة بخدماتك.',
    'Client Credit': 'رصيد العميل',
    'Bricoler Earnings': 'أرباح مقدم الخدمة',
    'Add a promo code': 'إضافة كود خصم',
    'Enter code here': 'أدخل الكود هنا',
    'Invalid promo code.': 'كود غير صالح.',
    'Promo code applied!': 'تم تطبيق الكود!',
    'Please log in first.': 'يرجى تسجيل الدخول أولاً.',
    'You have already used a referral code.': 'لقد استخدمت كود إحالة بالفعل.',
    'You cannot use your own code.': 'لا يمكنك استخدام الكود الخاص بك.',
    'Referral codes are only for new users.': 'أكواد الإحالة مخصصة للمستخدمين الجدد فقط.',
    'An error occurred.': 'حدث خطأ ما.',
    'This balance will be automatically applied to your next orders.': 'سيتم تطبيق هذا الرصيد تلقائياً على طلباتك القادمة.',
    'Share your referral code with friends to earn credits!': 'شارك كود الإحالة الخاص بك مع الأصدقاء لكسب الرصيد!',
    'These earnings can be withdrawn with your regular payouts.': 'يمكن سحب هذه الأرباح مع مدفوعاتك العادية.',
    'Share your code with other pros to earn bonuses!': 'شارك كودك مع محترفين آخرين لكسب مكافآت!',
    'Promote yourself!': 'روج لنفسك!',
    'Refer Clients': 'إحالة العملاء',
    'Refer Bricolers': 'إحالة مقدمي الخدمات',
    '50 MAD Reward': 'مكافأة 50 درهم',
    'Sign in to see code': 'سجل الدخول لرؤية الكود',
    'Copied': 'تم النسخ',
    'Copy': 'نسخ',

    // Order Submission Flow Extra
    'Search city...': 'ابحث عن مدينة...',
    'Search area...': 'ابحث عن منطقة...',
    'Morocco': 'المغرب',
    'Add': 'إضافة',
    'Pickup Location': 'موقع الاستلام',
    'Select your location': 'اختر موقعك',
    'Describe What you need': 'صف ما تحتاجه',
    '* Please include drop-off address and stairs/elevator details.': '* يرجى تضمين عنوان التوصيل وتفاصيل السلالم/المصعد.',
    'Example: I need to install a TV on a wall. I already have the bracket.': 'مثال: أحتاج إلى تثبيت تلفاز على الحائط. لدي الحامل بالفعل.',
    'Photos (Optional)': 'الصور (اختياري)',
    'Find Bricolers': 'ابحث عن محترفين',
    'Find your Tasker': 'ابحث عن المحترف الخاص بك',
    'No matching pros found': 'لم يتم العثور على محترفين مطابقين',
    'Try changing your location or post an open request.': 'حاول تغيير موقعك أو انشر طلباً مفتوحاً.',
    'Tasker': 'محترف',
    'Select a time slot': 'اختر فترة زمنية',
    'Choose your task date and start time. You can chat to adjust task details or change start time after confirming.': 'اختر تاريخ المهمة ووقت البدء. يمكنك الدردشة لتعديل تفاصيل المهمة أو تغيير وقت البدء بعد التأكيد.',
    'Request for:': 'طلب لـ:',
    'Next, confirm your details to get connected with your Tasker.': 'بعد ذلك، قم بتأكيد تفاصيلك للتواصل مع المحترف الخاص بك.',
    'Next Step': 'الخطوة التالية',
    'Your Bricol.ma Order': 'طلبك من Bricol.ma',
    'ORDER ID': 'رقم الطلب',
    'Choose your payment method': 'اختر طريقة الدفع',
    'On delivery': 'عند التسليم',
    'Bank Transfer': 'تحويل بنكي',
    'Upload receipt': 'رفع الإيصال',
    'Account Details': 'تفاصيل الحساب',
    'Bank:': 'البنك:',
    'Name:': 'الاسم:',
    'RIB:': 'رقم الحساب (RIB):',
    'Receipt attached': 'تم إرفاق الإيصال',
    'Tap to change': 'اضغط للتغيير',
    'Upload bank receipt': 'رفع إيصال التحويل',
    'JPG or PNG': 'JPG أو PNG',
    'Instructions': 'التعليمات',
    'No specific instructions.': 'لا توجد تعليمات محددة.',
    'Your Tasker': 'المحترف الخاص بك',
    'Trusted Pro': 'محترف موثوق',
    'Referral Credit': 'رصيد الإحالة',
    'Program Mission': 'برمجة المهمة',
    'Save Location': 'حفظ الموقع',
    'ELITE': 'نخبة',
    'PRO': 'محترف',
    'CLASSIC': 'كلاسيك',
    'Read More': 'اقرأ المزيد',
    'Already Selected': 'مختار بالفعل',
    'No portfolio photos yet': 'لا توجد صور أعمال سابقة',
    'Recent Reviews': 'التقييمات الأخيرة',
    'No reviews yet. Be the first to hire!': 'لا توجد تقييمات بعد. كن أول من يحجز!',
    'Client': 'عميل',
    'Recently': 'مؤخراً',
    'No comment left.': 'لا يوجد تعليق.',
    'Work Photos': 'صور الأعمال',
    'Equipments': 'المعدات',
    'About Me': 'نبذة عني',
    'No bio provided yet.': 'لا توجد نبذة شخصية بعد.',
    'Experience': 'الخبرة',
    'Missions': 'مهام',
    'reviews': 'تقييمات',
    'tasks': 'مهام',

    'Profile updated!': 'تم تحديث الملف الشخصي!',
    'Your profile changes have been saved.': 'تم حفظ تغييرات ملفك الشخصي.',
    'Jobs': 'المهام',

    // New additions from other views
    'Error': 'خطأ',
    'Failed to update profile': 'فشل تحديث الملف الشخصي',
    'Success': 'نجاح',
    'Availability updated!': 'تم تحديث أوقات العمل!',
    'Login failed.': 'فشل تسجيل الدخول.',
    'Review submitted!': 'تم إرسال التقييم!',
    'Thank you for rating the client.': 'شكراً لتقييم العميل.',
    'Failed to add service': 'فشل إضافة الخدمة',
    'Offer not sent.': 'لم يتم إرسال العرض.',
    'This job may no longer be available.': 'قد لا تكون هذه المهمة متاحة بعد الآن.',
    'Failed to send offer.': 'فشل إرسال العرض.',
    'Please try again.': 'يرجى المحاولة مرة أخرى.',
    'Counter offer not sent.': 'لم يتم إرسال العرض المقابل.',

    // Calendar & Availability extras
    'Availability Schedule': 'جدول أوقات العمل',
    'Saving...': 'جاري الحفظ...',
    'Save Changes': 'حفظ التغييرات',
    'Slots Active': 'فترات نشطة',
    'Pro Tip': 'نصيحة محترفة',
    'Select a date on the calendar, then toggle the working hours on the right side. Don\'t forget to save your changes!': 'اختر تاريخاً من التقويم، ثم فعل ساعات العمل على اليمين. لا تنس حفظ التغييرات!',

    // Bank & Payouts
    'Bank Name': 'اسم البنك',
    'Name on Bank Card': 'الاسم على بطاقة البنك',
    'Bank Details (optional)': 'بيانات البنك (اختياري)',
    'This info will be used to send your money directly to your account when you request a payout.': 'ستستخدم هذه المعلومات لإرسال أموالك مباشرة إلى حسابك عند طلب السحب.',
    'e.g. Attijariwafa Bank': 'مثل: التجاري وفا بنك',
    'Full name as on card': 'الاسم الكامل كما في البطاقة',
    '24-digit RIB or IBAN': 'رقم الحساب من 24 رقماً',
    'RIB / IBAN': 'رقم الحساب (RIB)',
    'Barid Bank': 'بريد بنك',
    'Al Barid Bank': 'بريد المغرب',
    'Abdelmalek Tahri': 'عبد الملك الطاهري',

    // Mission Details & Summary
    'Mission Fee': 'رسوم المهمة',
    'Final Earnings': 'الأرباح النهائية',
    'Your Net Payout': 'صافي أرباحك',
    'Quick Chat': 'دردشة سريعة',
    'Submit Rating': 'إرسال التقييم',
    'No specific instructions provided for this task.': 'لم يتم تقديم تعليمات محددة لهذه المهمة.',
    'Open in Maps': 'فتح في الخرائط',
    'Bank receipt attached': 'تم إرفاق وصل التحويل',
    'Verified Pro': 'محترف موثق',
    'Occupancy Rate': 'نسبة الإشغال',
    'No programmed jobs for this day': 'لا توجد مهام مبرمجة لهذا اليوم',
    'Most Picked': 'الأكثر اختياراً',
    'How was your experience?': 'كيف كانت تجربتك؟',
    'Action Required': 'مطلوب اتخاذ إجراء',
    'Estimated Payout': 'المبلغ المقدر',
    'No description provided.': 'لا يوجد وصف.',
    'Counter Offer': 'عرض مقابل',
    'Waiting': 'في الانتظار',
    'Job details': 'تفاصيل المهمة',
    'Upcoming': 'قادمة',
    'ID DE COMMANDE': 'رقم الطلب',
    'Your Earnings': 'أرباحك',
    'Unknown': 'غير معروف',
    'Work with client ': 'العمل مع العميل ',
    '. Feel free to chat for more details or location guidance.': '. لا تتردد في الدردشة لمزيد من التفاصيل أو التوجيه للموقع.',
    'Rate this Client': 'قيم هذا العميل',
    'Client behavior, timing...': 'سلوك العميل، المواعيد...',
    'SUN,MON,TUE,WED,THU,FRI,SAT': 'الأحد,الإثنين,الثلاثاء,الأربعاء,الخميس,الجمعة,السبت',
    'Handymen': 'عمال إصلاح',
    'Assemblers': 'مركبي أثاث',
    'Cleaners': 'منظفين',
    'Glass Cleaners': 'منظفي زجاج',
    'Plumbers': 'سباكين',
    'Electricians': 'كهربائيين',
    'Painters': 'صباغين',
    'Movers': 'عمال نقل',
    'Installers': 'مركبين',
    'Couriers': 'سعاة',
    'Gardeners': 'بستانيين',
    'Babysitters': 'جالسات أطفال',
    'Assistants': 'مساعدين',
    'Drivers': 'سائقين',
    'Professionals': 'محترفين',
    'Chefs': 'طهاة',
    'Private Drivers': 'سائقين خواص',
    'Tutors': 'مدرسين',
    'Tour Guides': 'مرشدين سياحيين',
    'Furniture Helper': 'مساعد تركيب أثاث',
    'Cleaning Helper': 'مساعد تنظيف',
    'Plumbing Service': 'خدمة سباكة',
    'Painting Service': 'خدمة صباغة',
    'Moving Helper': 'مساعد نقل',
    'Mounting Pro': 'محترف تثبيت',
    'Errands Helper': 'مساعد قضاء حاجات',
    'Gardening Helper': 'مساعد بستنة',
    'Caregiver': 'مقدم رعاية',
    'Courier Pro': 'ساعي محترف',
    'Airport Transfer': 'نقل من المطار',
    'Intercity Trip': 'رحلة بين المدن',
    'Learn Arabic': 'تعلم العربية',
    'Admin access granted!': 'تم منح صلاحية المسؤول!',
    'Admin access denied': 'تم رفض صلاحية المسؤول',
    'Wrong secret code': 'الرمز السري خاطئ',

    // Missing Services
    'Car Washing': 'غسيل السيارات',
    'Errands': 'قضاء حاجات',
    'Breakfast': 'إفطار',
    'Lunch': 'غداء',
    'Dinner': 'عشاء',
    'Moroccan Cooking Class': 'دروس طبخ مغربي',
    'Private Chef at Home': 'طباخ خاص في المنزل',
    'Moroccan Pastry Workshop': 'ورشة حلويات مغربية',
    'Market Tour & Cooking': 'جولة في السوق وطبخ',
    'Private Driver': 'سائق خاص',
    'Half-Day City Driver': 'سائق جولة نصف يوم',
    'Full-Day City Driver': 'سائق جولة يوم كامل',
    'VIP Airport Transfer': 'نقل مطار خاص (VIP)',
    'Intercity Trip Driver': 'سائق رحلات بين المدن',
    'Teach Arabic': 'تعليم اللغة العربية',
    'Intro to Moroccan Darija': 'مقدمة في الدارجة المغربية',
    'Conversational Practice': 'ممارسة المحادثة',
    'Arabic Calligraphy Intro': 'مقدمة في الخط العربي',
    'Survival Arabic for Tourists': 'العربية الأساسية للسياح',
    'Tour Guide': 'مرشد سياحي',
    'City Tour': 'جولة في المدينة',
    'Historical Sites Tour': 'جولة في المواقع التاريخية',
    'Moroccan Food Tour': 'جولة تذوق الطعام المغربي',
    'Medina Shopping Guide': 'دليل تسوق في المدينة العتيقة',

    // Onboarding Extra
    'What will your offer?': 'ماذا ستقدم؟',
    'Pick one or more Services and subservices.': 'اختر خدمة واحدة أو أكثر والخدمات الفرعية.',
    'Service Category': 'فئة الخدمة',
    'Add an hourly rate for this service (MAD)': 'أضف سعراً للساعة لهذه الخدمة (درهم)',
    'Tell clients why they should hire you for this service.': 'أخبر العملاء لماذا يجب عليهم توظيفك لهذه الخدمة.',
    'Describe your experience, your skills, or what makes your work special. (min. 50 characters)': 'صف خبرتك ومهاراتك وما يميز عملك. (50 حرفاً على الأقل)',
    'Experience (e.g. 5 Years)': 'الخبرة (مثال: 5 سنوات)',
    'I have my own equipments': 'لدي معداتي الخاصة',
    'I don\'t have any specialized equipment for this service': 'ليس لدي معدات متخصصة لهذه الخدمة',
    'Suggest equipments based on your services': 'اقتراح معدات بناءً على خدماتك',
    'Finish adding services': 'إنهاء إضافة الخدمات',
    'Activate Account': 'تفعيل الحساب',
    'Code Verified!': 'تم التحقق من الرمز!',
    'We found your profile. Let\'s complete it.': 'وجدنا ملفك الشخصي. لنكمله.',
    'Invalid code': 'رمز غير صالح',
    'This activation code does not exist.': 'رمز التفعيل هذا غير موجود.',
    'Successfully updated!': 'تم التحديث بنجاح!',
    'Sign-up failed': 'فشل التسجيل',
    'An error occurred during signup.': 'حدث خطأ أثناء التسجيل.',
    'Start working': 'ابدأ العمل',
    'Do you have an activation code?': 'هل لديك رمز تفعيل ؟',
    'If an admin created a shadow profile for you, enter your code here.': 'إذا قام مسؤول بإنشاء حساب لك، أدخل الرمز الخاص بك هنا.',
    'Yes, I have one': 'نعم، لدي واحد',
    'No, skip this': 'لا، تجاوز',
    'Verify and Continue': 'تحقق واستمر',
    'Go back': 'رجوع',
    "Hello 👋 I'm proficient in a wide range of services tailored to your needs. Fast and reliable work.": "مرحباً 👋 أنا متمكن من مجموعة واسعة من الخدمات لتلبية احتياجاتك. عمل سريع وموثوق.",

    // Areas
    'Ain Chock': 'عين الشق',
    'Ain Sebaa': 'عين السبع',
    'Anfa': 'أنفا',
    'Bernoussi': 'البرنوصي',
    'Ben M\'Sick': 'بن مسيك',
    'Derb Sultan': 'درب سلطان',
    'El Fida': 'الفداء',
    'Hay Hassani': 'الحي الحسني',
    'Hay Mohammadi': 'الحي المحمدي',
    'Maarif': 'المعاريف',
    'Mers Sultan': 'مرس السلطان',
    'Moulay Rachid': 'مولاي رشيد',
    'Sidi Bernoussi': 'سيدي البرنوصي',
    'Sidi Moumen': 'سيدي مومن',
    'Ain Diab': 'عين الدياب',
    'Bourgogne': 'بوركون',
    'California': 'كاليفورنيا',
    'Gauthier': 'غوتيه',
    'Racine': 'راسين',
    'Val Fleuri': 'فال فلوري',
    'Palmier': 'بالمييه',
    'Belvédère': 'بيلفيدير',
    'Roches Noires': 'روشنوار',
    'Zerktouni': 'الزرقطوني',
    'Guéliz': 'كليز',
    'Hivernage': 'ليفيرناج',
    'Mellah': 'الملاح',
    'Médina': 'المدينة',
    'Palmeraie': 'النخيل',
    'Riad Zitoun': 'رياض الزيتون',
    'Jemaa el-Fna': 'جامع الفنا',
    'Bab Doukkala': 'باب دكالة',
    'Massira': 'المسيرة',
    'Targa': 'تاركة',
    'M\'Hamid': 'المحاميد',
    'Agdal': 'أكدال',
    'Hassan': 'حسان',
    'Hay Riad': 'حي الرياض',
    'Souissi': 'السويسي',
    'Diour Jamaa': 'ديور الجامع',
    'Yaacoub El Mansour': 'يعقوب المنصور',
    'Kharbouch': 'خربوش',
    'Douar Iziki': 'دوار إيزيكي',
    'Daoudiate': 'الداوديات',
    'Amerchich': 'أمرشيش',
    'Sidi Youssef Ben Ali': 'سيدي يوسف بن علي',
    'Mabrouka': 'مبروكة',
    'Saada': 'سعادة',
    'Massira 1': 'المسيرة 1',
    'Massira 2': 'المسيرة 2',
    'Massira 3': 'المسيرة 3',
    'Abwab Marrakech': 'أبواب مراكش',
    'Hay Hassani (Marrakech)': 'الحي الحسني (مراكش)',
    'Azli': 'أزلي',
    'Sidi Abbad': 'سيدي عباد',
    'Izdihar': 'الازدهار',
    'Semlalia': 'جيليز - السملالية',
    'Victor Hugo': 'فيكتور هوغو',
    'Bab Kechich': 'باب كشيش',
    'Bab Ghemat': 'باب اغمات',
    'Bab Taghzout': 'باب تاغزوت',
    'Mestiri': 'المستيري',
    'Sidi Ghanem': 'سيدي غانم',
    'Route d\'Ourika': 'طريق أوريكا',
    'Route d\'Amizmiz': 'طريق أمزميز',
    'Route de Safi': 'طريق آسفي',
    'Route de Fes': 'طريق فاس',
    'Route de Casablanca': 'طريق الدار البيضاء',
    'Chrifia': 'الشريفية',
    'Bouskoura': 'بوسكورة',
    'Zenata': 'زناتة',
    'Dar Bouazza': 'دار بوعزة',
    'Tamaris': 'طماريس',
    'Mohammedia': 'المحمدية',
    'Sidi Rahal': 'سيدي رحال',
    'Had Soualem': 'حد السوالم',
    'Bouznika': 'بوزنيقة',
    'Skhirat': 'الصخيرات',
    'Temara': 'تمارة',
    'Sale': 'سلا',
    'Tamesna': 'تامسنا',
    'Ain Attiq': 'عين عتيق',
    'Harhoura': 'هرهورة',
    'Ocean': 'المحيط',
    'Souissi Area': 'منطقة السويسي',
    'Les Jardins': 'الحدائق',
    'Bir Kacem': 'بئر قاسم',
    'Villas': 'الفيلات',
    'Plateau': 'الهضبة',
    'Wifaq': 'الوفاق',
    'Hay El Fath': 'حي الفتح',

    // Extra Common UI
    'NEW': 'جديد',
    'for ': 'لـ ',
    'missions': 'مهام',

    // French keys support
    'Accueil': 'الرئيسية',
    'Profil': 'الملف الشخصي',
    'Commandes': 'الطلبات',
    'Mes Héros': 'أبطالي',
    'Historique des commandes': 'سجل الطلبات',
    'Mes informations': 'معلوماتي',
    'Passer en Mode Prestataire': 'التحويل إلى وضع مقدم الخدمة',
    'Langues et devise': 'اللغات والعملة',
    'Partagez et gagnez !': 'شارك واربح!',
    'Codes promo': 'أكواد الخصم',
    'Nettoyage de piscine': 'تنظيف المسبح',
    'Équilibre Chimique': 'توازن كيميائي',
    'Nettoyage du Filtre': 'تنظيف الفلتر',
    'Envoyer un message': 'إرسال رسالة',
    'Voir le profil': 'عرض الملف الشخصي',
    'Annuler la mission': 'إلغاء المهمة',
    'Missions programmées': 'المهام المبرمجة',
    'Aucune mission programmée': 'لا توجد مهام مبرمجة',
    'Vos prochaines missions seront affichées ici': 'ستظهر مهامك القادمة هنا',
    'Missions en cours': 'المهام قيد التنفيذ',
    'Aucune mission en cours': 'لا توجد مهام قيد التنفيذ',
    'Les missions que vous exécutez actuellement apparaîtront ici': 'المهام التي تنفذها حالياً ستظهر هنا',
    'Missions livrées': 'المهام المكتملة',
    'Aucune mission livrée pour le moment': 'لا توجد مهام مكتملة حالياً',
    'Les missions que vous terminez avec succès apparaîtront ici': 'المهام التي أكملتها بنجاح ستظهر هنا',
    'Besoin de revoir vos missions passées ?': 'هل تريد مراجعة مهامك السابقة؟',
    'Voir l’historique de mes missions': 'اطلع على سجل مهامي',
    'Historique de mes missions': 'سجل مهامي',
    'Aucun historique pour le moment': 'لا يوجد سجل حالياً',
    'Vos commandes terminées et annulées apparaîtront ici.': 'ستظهر هنا طلباتك المكتملة والملغاة.',
    'Messages about your services will appear here': 'ستظهر هنا الرسائل المتعلقة بخدماتك.',
    'Start chatting about your service.': 'ابدأ الدردشة حول خدمتك.',
    'DESCRIPTION DE LA MISSION': 'وصف المهمة',
    'Connectez-vous pour voir vos messages': 'سجل الدخول لرؤية الرسائل',
    'Suivez vos conversations et les mises à jour de vos projets.': 'تابع محادثاتك وتحديثات مشاريعك.',
    'Envoyez un message pour commencer': 'أرسل رسالة للبدء',
    'Gains Pro': 'أرباح مقدم الخدمة',
    'Crédit Client': 'رصيد العميل',
    'Ajouter un code promo': 'إضافة كود خصم',
    'Entrez le code ici': 'أدخل الكود هنا',
    'Appliquer': 'تطبيق',
    'Veuillez vous connecter d\'abord.': 'يرجى تسجيل الدخول أولاً.',
    'Vous avez déjà utilisé un code de parrainage.': 'لقد استخدمت كود إحالة بالفعل.',
    'Vous ne pouvez pas utiliser votre propre code.': 'لا يمكنك استخدام الكود الخاص بك.',
    'Les codes de parrainage sont réservés aux nouveaux utilisateurs.': 'أكواد الإحالة مخصصة للمستخدمين الجدد فقط.',
    'Code promo invalide.': 'كود غير صالح.',
    'Une erreur s\'est produite.': 'حدث خطأ ما.',
    'Ce solde sera automatiquement appliqué à vos prochaines commandes.': 'سيتم تطبيق هذا الرصيد تلقائياً على طلباتك القادمة.',
    'Partagez votre code de parrainage avec vos amis pour gagner des crédits !': 'شارك كود الإحالة الخاص بك مع الأصدقاء لكسب الرصيد!',
    'Partagez votre code avec d\'autres pros pour gagner des bonus !': 'شارك كودك مع محترفين آخرين لكسب مكافآت!',
    'Ces gains peuvent être retirés avec vos paiements réguliers.': 'يمكن سحب هذه الأرباح مع مدفوعاتك العادية.',
    'Promouvez-vous !': 'روج لنفسك!',
    'Parrainez des clients': 'إحالة العملاء',
    'Parrainez des pros': 'إحالة المحترفين',
    '50 MAD Bonus': 'مكافأة 50 درهم',
    'Connectez-وز pour voir': 'سجل الدخول لرؤية الكود',
    'Copié': 'تم النسخ',
    'Copier': 'نسخ',

    // Provider Dashboard & Performance
    'Global Performance': 'الأداء العام',
    'Complete more missions to boost your score': 'أكمل المزيد من المهام لتحسين تقييمك',
    'You are among the top tier providers!': 'أنت من بين أفضل مزودي الخدمة!',
    'Tips on how to make more money on Lbricol': 'نصائح لكسب المزيد من المال على لبريكول',
    'Get more clicks': 'احصل على المزيد من النقرات',
    'Pricing': 'التسعير',
    'Optimize rates': 'حسن أسعارك',
    'Commissions': 'العمولات',
    'Settle Commissions': 'تسوية العمولات',
    'Visibility': 'الظهور',
    'Efficiency': 'الكفاءة',
    'Rating': 'التقييم',
    'Reviews': 'التقييمات',
    'Net Earnings': 'صافي الأرباح',
    'Starter': 'مبتدئ',
    'Services': 'الخدمات',
    'Add Service': 'إضافة خدمة',
    'My portfolio': 'معرض أعمالي',
    'Portfolio': 'معرض الأعمال',
    'Work Areas': 'مناطق العمل',
    'Work areas': 'مناطق العمل',
    'Edit Service': 'تعديل الخدمة',
    'Delete Service': 'حذف الخدمة',
    'Active': 'نشط',
    'Inactive': 'غير نشط',
    'Sub-services': 'الخدمات الفرعية',
    'sub-services': 'خدمات فرعية',
    'services offered': 'خدمات مقدمة',
    'tools used': 'أدوات مستخدمة',
    '1 services offered': '1 خدمات فرعية مقدمة',
    '3 tools used': '3 أدوات مستخدمة',
    'Year 1': 'سنة واحدة',
    'Year 2': 'سنتان',
    'Year 3': '3 سنوات',
    'Year 4': '4 سنوات',
    'Year 5+': '5 سنوات فأكثر',
    'Total Gross': 'إجمالي الأرباح',
    'Platform Fee': 'رسوم المنصة',
    'Personal Profits': 'الأرباح الشخصية',
    'Live': 'مباشرة',
    'This is the net amount after platform fees based on your completed missions.': 'هذا هو المبلغ الصافي بعد خصم رسوم المنصة بناءً على مهامك المكتملة.',
    'Commission Settlement': 'تسوية العمولات',
    'Settling your commissions weekly keeps your profile at the top of search results.': 'تسوية عمولاتك أسبوعياً تبقي ملفك الشخصي في صدارة نتائج البحث.',
    'Reliability Score': 'درجة الموثوقية',

    // Fallbacks for profile fields
    'N/A': 'غير متوفر',
    'Not set': 'غير محدد',
    'Read Only': 'قراءة فقط',
    'Full Name': 'الاسم الكامل',
    'Email address': 'البريد الإلكتروني',
    'Phone number': 'رقم الهاتف',
    'Cardholder Name': 'اسم صاحب البطاقة',
    'Change password': 'تغيير كلمة المرور',
    'Change phone number': 'تغيير رقم الهاتف',
    'Payment methods': 'طرق الدفع',
    'Invoice information': 'معلومات الفاتورة',
    'Manage privacy': 'إدارة الخصوصية',
    'Admins': 'الإدارة',
    'Administration': 'الإدارة',
    'Exit Admin Mode': 'الخروج من وضع الإدارة',
    'Create Bricoler Profile': 'إنشاء ملف مقدم خدمة',
    'Support 24/7': 'دعم 24/7',
    'Chat with us': 'تحدث معنا',

    // Service Categories fallback gaps
    'Daily Service': 'خدمة يومية',
    'Hourly Service': 'خدمة بالساعة',
    'Event Transportation': 'النقل للمناسبات',
    'Grocery Shopping': 'تسوق البقالة',
    'Pharmacy Pickup': 'استلام من الصيدلية',
    'General Pickup & Drop-off': 'استلام وتوصيل عام',
    'Post Office / Mailing': 'مكتب البريد / المراسلات',
    'In-store Returns': 'إرجاع المشتريات',

    // Onboarding Status
    'Saving changes...': 'جاري حفظ التغييرات...',
    'Uploading media...': 'جاري تحميل الوسائط...',
    'Syncing...': 'جاري المزامنة...',
    'Authenticating...': 'جاري التحقق من الهوية...',
    'Preparing profile...': 'جاري تجهيز الملف الشخصي...',
    'Saving profile...': 'جاري حفظ الملف الشخصي...',
    'Finalizing...': 'جاري الإنهاء...',
    'Redirecting...': 'جاري إعادة التوجيه...',
    'Uploading Portfolio...': 'جاري تحميل معرض الأعمال...',
    'General Furniture Assembly': 'تركيب أثاث عام',
    'IKEA / Flat-Pack Assembly': 'تركيب أثاث إيكيا / القطع الجاهزة',
    'Crib Assembly': 'تركيب سرير أطفال',
    'Bookshelf Assembly': 'تركيب أرفف كتب',
    'Desk Assembly': 'تركيب مكتب',
    'Kitchen assembly': 'تركيب مطبخ',
    'Wardrobe assembly': 'تركيب خزانة ملابس',
    'Outdoor furniture assembly': 'تركيب أثاث خارجي',
    'Office furniture assembly': 'تركيب أثاث مكتبي',

    // Sub-services and Equipment Suggestions
    'Local Moving': 'نقل محلي',
    'Packing Services': 'خدمات التعبئة والتغليف',
    'Furniture Moving Only': 'نقل الأثاث فقط',
    'Regular Babysitting': 'جليسة أطفال عادية',
    'After-School Care': 'رعاية بعد المدرسة',
    'Night Sitting': 'رعاية ليلية',
    'Day Out Supervision': 'مرافقة نهارية',
    'General Repairs': 'إصلاحات عامة',
    'Door & Lock Repair': 'إصلاح الأبواب والأقفال',
    'Furniture Fixes': 'إصلاح الأثاث',
    'Shelf Mounting': 'تركيب الأرفف',
    'Caulking & Grouting': 'سد الثقوب واللحام',
    'TV Mounting': 'تركيب التلفاز',
    'Shelf Installation': 'تركيب الأرفف',
    'Curtain Rod Installation': 'تركيب قضبان الستائر',
    'Mirror Hanging': 'تعليق المرايا',
    'Picture Hanging': 'تعليق الصور',
    'Leak Repair': 'إصلاح التسربات',
    'Pipe Installation': 'تركيب الأنابيب',
    'Drain Cleaning': 'تنظيف المجاري',
    'Faucet Repair': 'إصلاح الصنابير',
    'Toilet Repair': 'إصلاح المراحيض',
    'Wiring & Rewiring': 'التوصيلات الكهربائية',
    'Outlet Installation': 'تركيب المقابس',
    'Light Fixture Installation': 'تركيب المصابيح',
    'Circuit Breaker Repair': 'إصلاح قاطع التيار',
    'Indoor Painting': 'صباغة داخلية',
    'Wallpapering': 'تركيب ورق الجدران',
    'Outdoor Painting': 'صباغة خارجية',
    'Concrete & Brick Painting': 'صباغة الخرسانة والطوب',
    'Accent Wall Painting': 'صباغة جدار مميز',
    'Wallpaper Removal': 'إزالة ورق الجدران',
    'Door, Cabinet, & Furniture Repair': 'إصلاح الأبواب والخزائن والأثاث',
    'Wall Repair': 'إصلاح الجدران',
    'Sealing & Caulking': 'الختم واللحام',
    'Appliance Installation & Repairs': 'تركيب وإصلاح الأجهزة',
    'Window & Blinds Repair': 'إصلاح النوافذ والستائر',
    'Flooring & Tiling Help': 'المساعدة في الأرضيات والتبليط',
    'Electrical Help': 'مساعدة كهربائية',
    'Plumbing Help': 'مساعدة في السباكة',
    'Light Carpentry': 'نجارة خفيفة',
    'Window Winterization': 'عزل النوافذ',
    'Family Home Cleaning': 'تنظيف المنازل',
    'Airbnb Cleaning': 'تنظيف شقق الإيجار',
    'Car washing': 'غسل السيارات',
    'Car Detailing': 'تنظيف عميق للسيارات',
    'Deep Home Cleaning': 'تنظيف عميق للمنازل',
    'Residential Glass': 'زجاج منزلي',
    'Commercial/Office Glass': 'زجاج مكاتب وتجاري',
    'Automotive Glass': 'زجاج السيارات',
    'Specialty/Hard-to-Clean Glass': 'زجاج خاص / صعب التنظيف',
    'Alternative Surfaces (Mirrors, Stainless Steel)': 'أسطح بديلة (مرايا، فولاذ)',
    'Lawn Mowing': 'جز العشب',
    'Tree Trimming': 'تقليم الأشجار',
    'Planting & Landscaping': 'الزرع وتنسيق الحدائق',
    'Skimming & Vacuuming': 'قشط وكنس المسبح',
    'Opening / Closing': 'افتتاح / إغلاق المسمح',
    'Tile & Wall Brushing': 'تنظيف الحيان والبلاط',
    'Dog Walking': 'مشي الكلاب',
    'Pet Sitting': 'مجالسة الحيوانات الأليفة',
    'Pet Grooming': 'تنظيف وتزيين الحيوانات',
    'Feeding & Check-ins': 'الإطعام والتفقد',
    'Pet Transportation': 'نقل الحيوانات الأليفة',
    'Companionship & Visits': 'المرافقة والزيارات',
    'Personal Assistance': 'المساعدة الشخصية',
    'Medication Reminders': 'التذكير بالمواعيد الطبية',
    'Meal Preparation': 'تحضير الطعام',
    'Light Housekeeping': 'أعمال منزلية خفيفة',
    'Transportation & Errands': 'النقل والمهمات',

    // Tools
    'Vacuum cleaner': 'مكنسة كهربائية',
    'Steam mop': 'ممسحة بخارية',
    'Microfiber cloths': 'أقمشة ميكروفايبر',
    'Eco cleaning products': 'منتجات تنظيف صديقة للبيئة',
    'Pressure washer': 'آلة غسل بالضغط',
    'Mop & bucket set': 'طقم ممسحة ودلو',
    'Squeegee & bucket': 'ممسحة زجاج ودلو',
    'Deionized water-fed pole': 'عمود تزويد بالمياه منزوعة الأيونات',
    'Steam cleaner': 'منظف بالبخار',
    'Scrapers (paint/residue)': 'مكاشط (للصباغة/البقايا)',
    'Extension poles': 'أعمدة تمديد',
    'Microfiber towels': 'مناشف ميكروفايبر',
    'Pipe wrench set': 'طقم مفاتيح أنابيب',
    'Drain snake / auger': 'زنبرك تسليك المجاري',
    'Pressure gauge': 'مقياس الضغط',
    'Soldering kit': 'طقم لحام',
    'Thread sealant tape': 'شريط مانع للتسرب',
    'Plunger': 'مكبس المجاري',
    'Digital multimeter': 'مقياس رقمي متعدد',
    'Wire stripper': 'أداة تعرية الأسلاك',
    'Power drill': 'مثقاب كهربائي',
    'Electrical tape': 'شريط كهربائي',
    'Circuit tester': 'مختبر الدوائر الكهربائية',
    'Cable fish tape': 'سلك سحب الكابلات',
    'Paint rollers & trays': 'بكرات وصواني الطلاء',
    'Spray gun': 'مسدس رش',
    'Brush set': 'طقم فرش',
    'Masking tape': 'شريط لاصق للطلاء',
    'Sandpaper set': 'ورق صنفرة',
    'Drop cloths': 'أغطية واقية',
    'Ladder': 'سلم',
    'Screwdriver set': 'طقم مفاتيح مفكات',
    'Level': 'ميزان فحص الاستواء',
    'Hammer & nails': 'مطرقة ومسامير',
    'Measuring tape': 'شريط قياس',
    'Jigsaw / circular saw': 'منشار أركت / دائري',
    'Allen key set': 'طقم مفاتيح ألن',
    'Rubber mallet': 'مطرقة مطاطية',
    'Cable ties': 'روابط كابلات',
    'Stud finder': 'جهاز كشف المسامير في الجدران',
    'Laser level': 'ميزان ليزر',
    'Wall anchor kit': 'طقم مثبتات جدران',
    'Cable management clips': 'مشابك تنظيم الكابلات',
    'VESA mount adapters': 'محولات تركيب VESA',
    'Drill & bits': 'مثقاب ورؤوس',
    'Pipe wrench': 'مفتاح أنابيب',
    'Voltage tester': 'مختبر الجهد',
    'Hosepipe connections': 'وصلات خراطيم',
    'Teflon tape': 'شريط تيفلون',
    'Bubble level': 'ميزان فقاعي',
    'Moving blankets': 'أغطية حماية الأثاث',
    'Hand truck / dolly': 'عربة يدوية للنقل',
    'Packing tape': 'شريط تغليف',
    'Stretch wrap': 'غلاف بلاستيكي مطاطي',
    'Moving straps': 'أحزمة نقل الأثاث',
    'Furniture sliders': 'قواعد تحريك الأثاث',
    'Lawn mower': 'جزازة عشب',
    'Hedge trimmer': 'مقص سياج الشجر',
    'Pruning shears': 'مقص تقليم',
    'Garden hose': 'خرطوم حديقة',
    'Rake & shovel set': 'طقم مجرفة ومذراة',
    'Wheelbarrow': 'عربة حديقة',
    'Pool skimmer / net': 'شبكة قشط المسابح',
    'Telescopic pole': 'عمود تلسكوبي',
    'Pool brush set': 'طقم فرش مسابح',
    'Water testing kit (DPD)': 'طقم اختبار المياه',
    'Vacuum head & hose': 'رأس خرطوم مكنسة المسبح',
    'Chemical dispenser': 'موزع مواد كيميائية',
    'Leashes & harnesses': 'مقاود وأطواق',
    'Pet grooming kit': 'طقم تنظيف الحيوانات',
    'Portable water bowl': 'وعاء ماء محمول',
    'Pet first aid kit': 'طقم إسعافات أولية للحيوانات',
    'Waste bags': 'أكياس نفايات',
    'Pet safe treats': 'مكافآت آمنة للحيوانات',
    'Child safety gear': 'معدات سلامة للأطفال',
    'Educational toys': 'ألعاب تعليمية',
    'Board games': 'ألعاب لوحية',
    'Art & craft supplies': 'لوازم فنية ويدوية',
    'Car seat (for transport)': 'مقعد سيارة (للنقل)',
    'Blood pressure monitor': 'جهاز قياس ضغط الدم',
    'Mobility aids (walker/cane)': 'وسائل مساعدة على المشي (مشاية/عصا)',
    'Medication organizer': 'منظم أدوية',
    'Emergency alert device': 'جهاز تنبيه للطوارئ',
    'Comfortable footwear': 'أحذية مريحة',
};

const FRENCH_OVERRIDES: Record<string, string> = {
    // Services (Main Categories)
    'Handyman': 'Bricolage',
    'Cleaning': 'Nettoyage',
    'Plumbing': 'Plomberie',
    'Electricity': 'Électricité',
    'Painting': 'Peinture',
    'Furniture assembly': 'Montage de meubles',
    'Moving help': 'Aide au déménagement',
    'Mounting': 'Fixation',
    'Gardening': 'Jardinage',
    'Babysitting': 'Baby-sitting',
    'Elderly assistance': 'Aide aux seniors',
    'Elderly care': 'Aide aux seniors',
    'Car with driver': 'Voiture avec chauffeur',
    'Car rental': 'Location de voiture',
    'Courier / delivery': 'Coursier / Livraison',
    'Airport pickup': 'Transfert aéroport',
    'Intercity transport': 'Transport interurbain',
    'Cooking': 'Cuisine',
    'Home Repairs': 'Réparations domicile',
    'Errands & small deliveries': 'Courses & Livraisons',
    'Errands': 'Courses',
    'Glass cleaning': 'Nettoyage de vitres',
    'Private Driver': 'Chauffeur privé',
    'Learn Arabic': 'Apprendre l\'arabe',
    'Tour Guide': 'Guide touristique',

    // Sub-services and common onboarding terms
    'General Furniture Assembly': 'Montage général de meubles',
    'IKEA / Flat-Pack Assembly': 'Montage IKEA / Meubles en kit',
    'Crib Assembly': 'Montage de berceau',
    'Bookshelf Assembly': 'Montage d\'étagère',
    'Desk Assembly': 'Montage de bureau',
    'Kitchen assembly': 'Montage de cuisine',
    'Wardrobe assembly': 'Montage d\'armoire',
    'Outdoor furniture assembly': 'Montage de meubles d\'extérieur',
    'Office furniture assembly': 'Montage de meubles de bureau',
    'Local Moving': 'Déménagement local',
    'Packing Services': 'Services d\'emballage',
    'Furniture Moving Only': 'Déménagement de meubles uniquement',
    'Regular Babysitting': 'Baby-sitting régulier',
    'After-School Care': 'Garde après l\'école',
    'Night Sitting': 'Garde de nuit',
    'Day Out Supervision': 'Accompagnement sortie',
    'General Repairs': 'Réparations générales',
    'Door & Lock Repair': 'Réparation de porte & serrure',
    'Furniture Fixes': 'Réparation de meubles',
    'Shelf Mounting': 'Fixation d\'étagère',
    'Caulking & Grouting': 'Calfeutrage & Jointoiement',
    'TV Mounting': 'Fixation TV',
    'Shelf Installation': 'Installation d\'étagère',
    'Curtain Rod Installation': 'Installation de tringle à rideaux',
    'Mirror Hanging': 'Pose de miroir',
    'Picture Hanging': 'Accrochage de tableaux',
    'Leak Repair': 'Réparation de fuites',
    'Pipe Installation': 'Installation de tuyauterie',
    'Drain Cleaning': 'Débouchage de canalisation',
    'Faucet Repair': 'Réparation de robinet',
    'Toilet Repair': 'Réparation de toilettes',
    'Wiring & Rewiring': 'Câblage & Recâblage',
    'Outlet Installation': 'Installation de prises',
    'Light Fixture Installation': 'Installation de luminaires',
    'Circuit Breaker Repair': 'Réparation de disjoncteur',
    'Indoor Painting': 'Peinture intérieure',
    'Wallpapering': 'Pose de papier peint',
    'Outdoor Painting': 'Peinture extérieure',
    'Concrete & Brick Painting': 'Peinture béton & briques',
    'Accent Wall Painting': 'Peinture de mur d\'accent',
    'Wallpaper Removal': 'Décollage de papier peint',
    'Door, Cabinet, & Furniture Repair': 'Réparation de portes & placards',
    'Wall Repair': 'Réparation de murs',
    'Sealing & Caulking': 'Scellage & Calfeutrage',
    'Appliance Installation & Repairs': 'Installation & Réparation d\'appareils',
    'Window & Blinds Repair': 'Réparation fenêtres & stores',
    'Flooring & Tiling Help': 'Aide pose sol & carrelage',
    'Electrical Help': 'Aide électricité',
    'Plumbing Help': 'Aide plomberie',
    'Light Carpentry': 'Petite menuiserie',
    'Window Winterization': 'Isolation de fenêtres',
    'Family Home Cleaning': 'Nettoyage domicile familial',
    'Airbnb Cleaning': 'Nettoyage Airbnb',
    'Car washing': 'Lavage auto',
    'Car Detailing': 'Nettoyage complet auto',
    'Deep Home Cleaning': 'Nettoyage approfondi',
    'Residential Glass': 'Vitres résidentielles',
    'Commercial/Office Glass': 'Vitres bureaux/commerces',
    'Automotive Glass': 'Vitrage automobile',
    'Specialty/Hard-to-Clean Glass': 'Vitres spéciales/difficiles',
    'Alternative Surfaces (Mirrors, Stainless Steel)': 'Surfaces alternatives (Miroirs)',
    'Lawn Mowing': 'Tonte de pelouse',
    'Tree Trimming': 'Taille d\'arbres',
    'Planting & Landscaping': 'Plantation & Paysagisme',
    'Skimming & Vacuuming': 'Nettoyage surface & aspiration',
    'Opening / Closing': 'Ouverture / Fermeture piscine',
    'Tile & Wall Brushing': 'Brossage parois & carrelage',
    'Dog Walking': 'Promenade de chiens',
    'Pet Sitting': 'Garde d\'animaux',
    'Pet Grooming': 'Toilettage d\'animaux',
    'Feeding & Check-ins': 'Repas & Visites',
    'Pet Transportation': 'Transport d\'animaux',
    'Companionship & Visits': 'Compagnie & Visites',
    'Personal Assistance': 'Assistance personnelle',
    'Medication Reminders': 'Rappel de médicaments',
    'Meal Preparation': 'Préparation de repas',
    'Light Housekeeping': 'Ménage léger',
    'Transportation & Errands': 'Transport & Courses',
    'Breakfast': 'Petit déjeuner',
    'Lunch': 'Déjeuner',
    'Dinner': 'Dîner',
    'Moroccan Cooking Class': 'Cours de cuisine marocaine',
    'Private Chef at Home': 'Chef privé à domicile',
    'Moroccan Pastry Workshop': 'Atelier pâtisserie marocaine',
    'Market Tour & Cooking': 'Tour du marché & Cuisine',
    'Half-Day City Driver': 'Chauffeur ville demi-journée',
    'Full-Day City Driver': 'Chauffeur ville journée',
    'VIP Airport Transfer': 'Transfert aéroport VIP',
    'Intercity Trip Driver': 'Chauffeur interurbain',
    'Intro to Moroccan Darija': 'Intro à la Darija marocaine',
    'Conversational Practice': 'Pratique conversationnelle',
    'Arabic Calligraphy Intro': 'Intro à la calligraphie arabe',
    'Survival Arabic for Tourists': 'Arabe de survie pour touristes',
    'City Tour': 'Tour de ville',
    'Historical Sites Tour': 'Tour des sites historiques',
    'Moroccan Food Tour': 'Tour gastronomique',
    'Medina Shopping Guide': 'Guide shopping Médina',
    'Availability': 'Disponibilités',
    'Availability Schedule': 'Planning des disponibilités',
    'Availability updated!': 'Disponibilités mises à jour !',
    'Summary': 'Récapitulatif',
    'Task Fee': 'Frais de mission',
    'Lbricol Fee': 'Frais Lbricol',
    'Total': 'Total',
    'Booking Breakdown': 'Détail de la réservation',
    'Budget Breakdown': 'Détail du budget',
    'Additional Details': 'Détails supplémentaires',
    'Contact via WhatsApp': 'Contacter via WhatsApp',
    'New mission': 'Nouvelle mission',
    'Scheduled': 'Programmée',
    'Delivered': 'Livrée',
    'Completed': 'Terminée',
    'Accepted': 'Acceptée',
    'Declined': 'Refusée',
    'In Progress': 'En cours',
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('fr');

    React.useEffect(() => {
        const savedLang = localStorage.getItem('lbricol_language');
        if (savedLang === 'en' || savedLang === 'fr' || savedLang === 'ar') {
            setLanguage(savedLang as Language);
        } else {
            // Use French as default session language if no preference is saved, 
            // but do NOT save it to localStorage yet so we can detect first-timers.
            setLanguage('fr');
        }
    }, []);

    React.useEffect(() => {
        const root = document.documentElement;
        const rtl = language === 'ar';

        root.setAttribute('lang', language);
        root.setAttribute('dir', rtl ? 'rtl' : 'ltr');
        root.classList.toggle('rtl', rtl);
        root.classList.toggle('ltr', !rtl);
    }, [language]);

    const handleSetLanguage = (lang: Language) => {
        localStorage.setItem('lbricol_language', lang);
        setLanguage(lang);
    };

    const t = (translation: Translation) => {
        if (language === 'ar') {
            if (translation.ar && translation.ar.trim().length > 0) return translation.ar;
            const mapped = ARABIC_OVERRIDES[translation.en] || ARABIC_OVERRIDES[translation.fr];
            if (mapped) return mapped;
            // Avoid mixed French UI in Arabic mode when a key is still missing.
            return translation.en;
        }
        if (language === 'fr') {
            if (translation.fr && translation.fr.trim().length > 0 && translation.fr !== translation.en) return translation.fr;
            const mapped = FRENCH_OVERRIDES[translation.en];
            if (mapped) return mapped;
            return translation.fr || translation.en;
        }
        return translation.en;
    };

    const isRTL = language === 'ar';

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isRTL }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
